services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: patent-protector-2024
      POSTGRES_USER: patent-protector-2024
      POSTGRES_PASSWORD: patent-protector-2024
    volumes:
      - './storage/db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 60s
      retries: 10
